export const COLLECTION_ACTION_TYPES = {
    FETCH_COLLECTIONS_START: 'collections/FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS: 'collections/FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAIL: 'collections/FETCH_COLLECTIONS_FAIL',
} 